# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ROBOT2R.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from InverseKinematics2R import * 
from ForwardKinematics2R import *
import math
import numpy
from sympy import *
import matplotlib.pyplot as plt
import time 
import os
import sys

# --- NUEVA SECCIÃƒâ€œN DE HARDWARE PARA PCA9685 ---
try:
    import board
    import busio
    from adafruit_pca9685 import PCA9685
    from adafruit_motor import servo


    i2c = busio.I2C(board.SCL, board.SDA)
    pca = PCA9685(i2c)
    pca.frequency = 50

    # Definimos los servos en los canales 0 y 1 de la placa azul
    # Ajustamos el pulse_width para que coincida con tus servos anteriores
    SERVO_1 = servo.Servo(pca.channels[0], min_pulse=500, max_pulse=2500)
    SERVO_2 = servo.Servo(pca.channels[1], min_pulse=500, max_pulse=2500)
    
except Exception as e:
    print(f"Error de Hardware: {e}")
    SERVO_1 = SERVO_2 = None
# ----------------------------------------------

# Dimensiones para 2R
l1 = 10.7
l2 = 10.3
Px=0
Py=0
n = 10
x = numpy.arange(1, n + 1, 1)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 241, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 121, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 121, 21))
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(160, 40, 71, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_2.setGeometry(QtCore.QRect(160, 80, 71, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(80, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 80, 311, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 30, 121, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 30, 121, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 140, 111, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 171, 31))
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 140, 161, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(600, 80, 181, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 40, 141, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 90, 111, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(280, 280, 501, 341))
        self.graphicsView.setObjectName("graphicsView")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 370, 221, 111))
        self.label_9.setText("")
        ruta_base = os.path.dirname(os.path.abspath(__file__))
        ruta_logo = os.path.join(ruta_base, "ecci.jpg")
        self.label_9.setPixmap(QtGui.QPixmap(ruta_logo))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 340, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 320, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 300, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.manual)
        self.pushButton_2.clicked.connect(self.dibujar_area)


        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CINEMATICA ROBOT 2R"))
        self.groupBox.setTitle(_translate("MainWindow", "MOVIMIENTO MANUAL"))
        self.label_2.setText(_translate("MainWindow", "POSICION EN X"))
        self.label_3.setText(_translate("MainWindow", "POSICION EN Y"))
        self.pushButton.setText(_translate("MainWindow", "MOVER"))
        self.groupBox_2.setTitle(_translate("MainWindow", "AREA DE TRABAJO Y NOMBRES"))
        self.pushButton_2.setText(_translate("MainWindow", "DIBUJAR AREA\n"
"   DE \n"
"TRABAJO"))
        self.pushButton_3.setText(_translate("MainWindow", "NOMBRES DE \n"
" LOS \n"
" INTEGRANTES"))
        self.pushButton_4.setText(_translate("MainWindow", "ESCRIBIR"))
        self.label_4.setText(_translate("MainWindow", "INGRESE UN NOMBRE"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "DIBUJO DE LOGOS"))
        self.pushButton_5.setText(_translate("MainWindow", "CARGAR IMAGEN"))
        self.pushButton_6.setText(_translate("MainWindow", "DIBUJAR"))
        self.label_7.setText(_translate("MainWindow", "ELECTIVA DE ROBOTICA"))
        self.label_8.setText(_translate("MainWindow", "BRAYAN CAMILO ROMERO BERNAL"))
        self.label_5.setText(_translate("MainWindow", "JOHAN SEBASTIAN FAJARDO PIRAQUIVE"))
        self.label_6.setText(_translate("MainWindow", "UNIVERSIDAD ECCI"))

    def manual(self):
        """FunciÃ³n para mover los servos directamente al objetivo sin interpolaciÃ³n"""
        try:
            # 1. Obtener destino desde los cuadros de texto
            target_x = float(self.textEdit.toPlainText())
            target_y = float(self.textEdit_2.toPlainText())

            # 2. Calcular cinemÃ¡tica inversa para el destino
            resultado_inv = InverseKinematics2R(l1, l2, target_x, target_y)
            
            if resultado_inv:
                th1_final, th2_final = resultado_inv
                
                # 3. Mover Servos fÃ­sicos directamente (en grados)
                if SERVO_1 and SERVO_2:
                    q1_deg = math.degrees(th1_final)
                    q2_deg = math.degrees(th2_final)
                    # LimitaciÃ³n de seguridad 0-180
                    SERVO_1.angle = max(0, min(180, q1_deg))
                    SERVO_2.angle = max(0, min(180, q2_deg))
                    print(f"Servos movidos a: q1={q1_deg:.2f}Â°, q2={q2_deg:.2f}Â°")

                # 4. Feedback visual: Graficar solo el punto final y el brazo
                plt.figure("PosiciÃ³n Manual Directa")
                plt.clf()
                
                # Obtener coordenadas con cinemÃ¡tica directa para verificar
                MTH = ForwardKinematics2R(l1, l2, th1_final, th2_final)
                px, py = MTH.t[0], MTH.t[1]

                plt.plot(px, py, 'ro', markersize=10, label='Destino Alcanzado')
                plt.xlabel('X')
                plt.ylabel('Y')
                plt.xlim(-25, 25)
                plt.ylim(-25, 25)
                plt.grid(True)
                plt.title(f'Movimiento Directo a X:{target_x}, Y:{target_y}')
                plt.legend()
                plt.show()
                
                print(f"Movimiento directo completado a X:{px:.2f} Y:{py:.2f}")
            else:
                print("Error: El punto estÃ¡ fuera del Ã¡rea de trabajo.")

        except ValueError:
            print("Error: Ingrese nÃºmeros vÃ¡lidos en los campos de posiciÃ³n.")
        except Exception as e:
            print(f"Error inesperado: {e}")


    def dibujar_area(self):
        # Dimensiones para 2R
        l1 = 10.7
        l2 = 10.3

        # CinemÃ¡tica inversa 2R (Solo Px y Py) - Siguiendo TU orden de parÃ¡metros
        # Punto 0
        P0x = 0.5
        P0y = 0.5
        [theta1_P0, theta2_P0] = InverseKinematics2R(l1, l2, P0x, P0y)

        # Punto 1
        P1x = 21
        P1y = 0
        [theta1_P1, theta2_P1] = InverseKinematics2R(l1, l2, P1x, P1y)

        # Punto 2
        P2x = -21
        P2y = 0
        [theta1_P2, theta2_P2] = InverseKinematics2R(l1, l2, P2x, P2y)

        # Punto 3
        P3x = -10
        P3y = -10
        [theta1_P3, theta2_P3] = InverseKinematics2R(l1, l2, P3x, P3y)

        # Punto 4
        P4x = -0.5
        P4y = -0.5
        [theta1_P4, theta2_P4] = InverseKinematics2R(l1, l2, P4x, P4y)

        n = 5
        x = numpy.arange(1, n + 1, 1)

        # InterpolaciÃ³n de 2 Ã¡ngulos Ãºnicamente
        theta1_P0toP1 = numpy.linspace(theta1_P0, theta1_P1, n)
        theta2_P0toP1 = numpy.linspace(theta2_P0, theta2_P1, n)
        theta1_P1toP2 = numpy.linspace(theta1_P1, theta1_P2, n)
        theta2_P1toP2 = numpy.linspace(theta2_P1, theta2_P2, n)
        theta1_P2toP3 = numpy.linspace(theta1_P2, theta1_P3, n)
        theta2_P2toP3 = numpy.linspace(theta2_P2, theta2_P3, n)
        theta1_P3toP4 = numpy.linspace(theta1_P3, theta1_P4, n)
        theta2_P3toP4 = numpy.linspace(theta2_P3, theta2_P4, n)

        # d almacenarÃ¡ X e Y (usamos 2 filas)
        d = numpy.zeros((2, n))

        fig1 = plt.figure()
        ax0 = fig1.add_subplot(111)
        ax0.set_xlabel('X')
        ax0.set_ylabel('Y')
        ax0.set_xlim(-25, 25)
        ax0.set_ylim(-25, 25)
        ax0.set_title('Trayectoria en Plano XY')
        ax0.grid(True)

        # --- BLOQUES SEPARADOS DE MOVIMIENTO Y DIBUJO ---
        for i in range(0, n):
            # Movimiento fÃ­sico (con conversiÃ³n a grados y protecciÃ³n)
            if SERVO_1 and SERVO_2:
                SERVO_1.angle = max(0, min(180, math.degrees(theta1_P0toP1[i])))
                SERVO_2.angle = max(0, min(180, math.degrees(theta2_P0toP1[i])))
            
            MTH = ForwardKinematics2R(l1, l2, theta1_P0toP1[i], theta2_P0toP1[i])
            d[0, i] = MTH.t[0]
            d[1, i] = MTH.t[1]    
            ax0.plot(d[0, i], d[1, i], '.b')


        for i in range(0, n):
            if SERVO_1 and SERVO_2:
                SERVO_1.angle = max(0, min(180, math.degrees(theta1_P1toP2[i])))
                SERVO_2.angle = max(0, min(180, math.degrees(theta2_P1toP2[i])))
                
            MTH = ForwardKinematics2R(l1, l2, theta1_P1toP2[i], theta2_P1toP2[i])
            d[0, i] = MTH.t[0]
            d[1, i] = MTH.t[1]    
            ax0.plot(d[0, i], d[1, i], '.b')


        for i in range(0, n):
            if SERVO_1 and SERVO_2:
                SERVO_1.angle = max(0, min(180, math.degrees(theta1_P2toP3[i])))
                SERVO_2.angle = max(0, min(180, math.degrees(theta2_P2toP3[i])))
                
            MTH = ForwardKinematics2R(l1, l2, theta1_P2toP3[i], theta2_P2toP3[i])
            d[0, i] = MTH.t[0]
            d[1, i] = MTH.t[1]    
            ax0.plot(d[0, i], d[1, i], '.b')


        for i in range(0, n):
            if SERVO_1 and SERVO_2:
                SERVO_1.angle = max(0, min(180, math.degrees(theta1_P3toP4[i])))
                SERVO_2.angle = max(0, min(180, math.degrees(theta2_P3toP4[i])))
                
            MTH = ForwardKinematics2R(l1, l2, theta1_P3toP4[i], theta2_P3toP4[i])
            d[0, i] = MTH.t[0]
            d[1, i] = MTH.t[1]    
            ax0.plot(d[0, i], d[1, i], '.b')
  

        plt.show(block=False)

        # GrÃ¡ficas de Espacio Articulacional y Operacional
        fig2 = plt.figure(2)
        ax1, ax2 = fig2.subplots(2, 1)

        ax1.plot(x, numpy.rad2deg(theta1_P1toP2), 'tab:red', label='q1')
        ax1.plot(x, numpy.rad2deg(theta2_P1toP2), 'tab:green', label='q2')
        ax1.set_title('Espacio articulacional')
        ax1.legend(loc="upper left")
        ax1.grid(True)

        ax2.plot(x, d[0, :], 'tab:red', label='X')
        ax2.plot(x, d[1, :], 'tab:green', label='Y')
        ax2.set_title('Espacio operacional')
        ax2.legend(loc="upper left")
        ax2.grid(True)

        plt.tight_layout()
        plt.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
